# Generated by Django 5.2.13 on 2026-04-27 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_test', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lesson',
            name='video_link',
        ),
        migrations.AddField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='LessonMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('material_type', models.CharField(choices=[('video', 'Видео'), ('presentation', 'Презентация'), ('text', 'Текст'), ('file', 'Файл')], max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='lesson_materials/')),
                ('url', models.URLField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='for_test.lesson')),
            ],
        ),
    ]
