# Generated by Django 5.2.13 on 2026-04-27 14:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_test', '0002_remove_lesson_video_link_lesson_description_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('avatar', models.ImageField(blank=True, default='avatars/default.png', upload_to='avatars/')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='productaccess',
            name='unique_user_product_access',
        ),
        migrations.AlterUniqueTogether(
            name='productaccess',
            unique_together={('user', 'product')},
        ),
        migrations.AddField(
            model_name='productaccess',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='productaccess',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='productaccess',
            name='granted_at',
        ),
    ]
